const String customerOnboarding = '@customerOnboarding';
const String customerSignIn = '@customerSignIn';
const String certificationRenew = '@certificationRenew';
const String resetPassword = '@resetPassword';
const String checkIn = '@checkIn';
const String checkInDiet = '@checkInDiet';
const String coachProfile = '@coachProfile';
const String tutorCertificationFlow = '@tutorCertificationFlow';
// const String providerFlowCleanup = 'providerFlowCleanup';
